stages:
  - Lint
  - Unit Test
  - Integration Test
  - Publish
  - Test Public

.packages_base:
  image: node
  before_script:
    - yarn install
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules

lint_packages:
  extends: .packages_base
  stage: Lint
  script: yarn lint
