.react_shared_base:
  image: node
  before_script:
    - cd packages/react-shared
    - yarn install
    - apt-get -qq update
    - apt-get install -y jq
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules

test_react_shared:
  extends: .react_shared_base
  stage: Unit Test
  script: yarn test

publish_react_shared:
  extends: .react_shared_base
  stage: Publish
  script:
    - cp ../../scripts/publish.sh .
    - echo "${NPMRC}" > .npmrc && ./publish.sh && rm .npmrc
    - rm publish.sh
