.example_audit_base:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  before_script:
    - cd examples/audit
    - npm ci --legacy-peer-deps
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules

test_example_audit_app:
  extends: .example_audit_base
  stage: Integration Test
  script:
    - npm run cypress:ci
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
