.pangea_node_sdk_base:
  before_script:
    - cd packages/pangea-node-sdk
    - yarn install
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - packages/pangea-node-sdk/**/*
      when: on_success

.pangea_node_sdk_publish:
  before_script:
    - cd packages/pangea-node-sdk
    - yarn install
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      changes:
        - packages/pangea-node-sdk/**/*
      when: on_success

lint_pangea_node_sdk:
  extends: .pangea_node_sdk_base
  stage: Lint
  script:
    - yarn lint

test_pangea_node_sdk:
  extends: .pangea_node_sdk_base
  stage: Unit Test
  script:
    - yarn test:unit

integration_pangea_node_sdk:
  extends: .pangea_node_sdk_base
  stage: Integration Test
  script:
    - yarn test:integration

publish_pangea_node_sdk_base:
  extends: .pangea_node_sdk_publish
  stage: Publish
  script:
    - yarn build
    - echo ${NPMRC} > .npmrc && npm publish && rm -rf .npmrc
